### PR TITLE
ROC-31

### PR DESCRIPTION
**Pull request by squaill**
- models
- easy peasy db migrations for weeks to come

Looks like a big pr but everything in /migrations is auto generated

### CODE REVIEW

**Comment by LarrySchultheis** [comment]
image

**Comment by squaill** [comment]
y no approve

**Comment by LarrySchultheis** [comment]
Haven't looked at it yet. Will in a lil

**Comment by LarrySchultheis** [comment]
Merging. Them models be bussin

**Review by LarrySchultheis — APPROVED** [review]

**Pull request merged**
